[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spine_multi"
version = "0.1.0"
description = ""
authors = [
    { name = "Zac", email = "zacravi@seas.upenn.edu" }
]
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = [
    "ultralytics",
]

[project.urls]
Homepage = "https://github.com/zacravichandran/language_teaming"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
