spine_multi_node:
  ros__parameters:
    namespace: ""
    planning_limit_idx: 5
    team_specification: "You have two clearpath jackal robots"
    init_graph:  /home/zac/projects/dcist/src/spine-multi/ros/spine_multi_ros/data/perch.json
    init_location: ground_1
    robots:
      robot1:
        name: jackal_1
        namespace: /callisto
        subscription_prefix: ""
        init_location: ground_1
        nav_target_frame: map
        graph_viz_topic: /callisto/graph_viz
        track_topic: /callisto/grounding_dino_node/tracks
        local_costmap_topic: /callisto/local_costmap/costmap
        vlm_request: /to_callisto/vlm_request
        vlm_response: /callisto/vlm_response
        vlm_ack: /to_callisto/vlm_ack
        navigation_request: /to_callisto/navigation_request
        navigation_status: /callisto/navigation_status
        navigation_ack: /to_callisto/navigation_ack
        label_request: /to_callisto/label_request 
        label_response: /callisto/label_response 
        label_ack: /to_callisto/label_ack
      robot2:
        name: jackal_2
        namespace: /io
        subscription_prefix: ""
        init_location: ground_1
        nav_target_frame: map
        graph_viz_topic: /io/graph_viz
        track_topic: /io/grounding_dino_node/tracks
        local_costmap_topic: /io/local_costmap/costmap
        vlm_request: /to_io/vlm_request
        vlm_response: /io/vlm_response
        vlm_ack: /to_io/vlm_ack
        navigation_request: /to_io/navigation_request
        navigation_status: /io/navigation_status
        navigation_ack: /to_io/navigation_ack
        label_request: /to_io/label_request 
        label_response: /io/label_response 
        label_ack: /to_io/label_ack
